# Use the official MySQL image
FROM mysql:8.0

# Copy the initialization script to the container
COPY ./docker/init.sql /docker-entrypoint-initdb.d/

# Set the correct permissions for the script
RUN chmod 644 /docker-entrypoint-initdb.d/init.sql

# Expose port 3306 (optional, as it's already exposed by the base image)
EXPOSE 3306
